WebApplication1/Models/HeadModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class HeadModel
    {
        public string UserName { get; set; }
        public string Time { get; set; }
    }

    public class DataModel
    {
        public int Input_a { get; set; }
        public int Input_b { get; set; }
        public int Result { get; set; }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Controllers/PlusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.ServiceReference1;

namespace WebApplication1.Controllers
{
    public class PlusController : Controller
    {
        // GET: Plus
        public ActionResult Index()
        {
            HeadModel head = new HeadModel { UserName = "Gao", Time = DateTime.Now.ToString() };
            ViewBag.head = head;
            ViewBag.result = "NULL";
            return View();
        }


        [HttpPost]
        public ActionResult Index(int? a, int? b)
        {
            HeadModel head = new HeadModel { UserName = "Gao", Time = DateTime.Now.ToString() };
            ViewBag.head = head;

            if (a != null && b != null)
            {
                Service1Client client = new Service1Client();
                string result = client.PlusNumber((int)a, (int)b);
                ViewBag.result = result;
            }
            else
                ViewBag.result = "NULL";
            return View();
        }

        public JsonResult TabPlus(int limit, int offset, int? input_a, int? input_b)
        {
            if (input_a != null && input_b != null)
            {
                Service1Client client = new Service1Client();
                string result = client.PlusNumber((int)input_a, (int)input_b);

                var data1 = new[]{
                    new DataModel { Input_a = (int)input_a, Input_b = (int)input_b, Result = int.Parse(result) },
                };

                //var list = new List<DataModel>();              
                //list.Add(data1);
                //var total = list.Count;
                //var rows = list.Skip(offset).Take(limit).ToList();
                //return Json(new { total = total, rows = rows }, JsonRequestBehavior.AllowGet);

                return Json(new { tatal = 1, rows = data1.ToList() }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { total = 0, rows = 0 }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LabPlus(int? input_a, int? input_b)
        {
            if (input_a != null && input_b != null)
            {
                Service1Client client = new Service1Client();
                string result = client.PlusNumber((int)input_a, (int)input_b);

                var data1 = new[]{
                    new DataModel { Input_a = (int)input_a, Input_b = (int)input_b, Result = int.Parse(result) },
                };
                return Json(data1.ToList(), JsonRequestBehavior.AllowGet);
            }
            else
            {
                var data1 = new[]{
                    new DataModel { Input_a = 0, Input_b = 0, Result = 0 },
                };
                return Json(data1.ToList(), JsonRequestBehavior.AllowGet);
            }              
        }
    }
}

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication1/Views/Plus/Index.cshtml
@{
    ViewBag.Title = "加法计算";
}

<section>
    <h2>@ViewBag.head.UserName</h2>
    <p>@ViewBag.head.Time</p>
</section>

<section>
    <p>@ViewBag.result</p>
    @using (Html.BeginForm("Index", "Plus", FormMethod.Post))
    {
        <p>
            <input id="a" name="a" type="text" />+<input id="b" name="b" type="text" /><br>
            <input id="submit_txt" type="submit" />
        </p>
    }
</section>

<section>
    <div>
        <form class="form-inline">
            <div class="input-group">
                <input id="input_a" type="text" />
                <input id="input_b" type="text" />
            </div>
            <div class="btn-group">
                <button id="btn_cal" type="button" class="btn btn-default">查询
                    @*<span class="fade fa-serach" aria-hidden="true">&nbsp;查询</span>*@
                </button>
            </div>
        </form>
    </div>

    <div>
        <table id="tab_result"></table>
    </div>
</section>

<section>
    <form class="form-inline">
        <div class="input-group">
            <input id="lab_a" type="text" />
            <input id="lab_b" type="text" />
        </div>
        <div class="btn-group">
            <button id="btn_lab" type="button" class="btn btn-default">计算</button>
        </div>
    </form>
    <label id="lab_result">NULL</label>
</section>

@section Scripts {
    <script src="~/Scripts/APP/test.js"></script>
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @Scripts.Render("~/bundles/bootstrap-table")
</body>
</html>